# Generated by Django 3.0.5 on 2020-06-02 15:09

import datetime
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInifo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50, verbose_name='审计单位名称')),
                ('company_code', models.CharField(max_length=20, verbose_name='组织机构代码证号')),
                ('company_department', models.CharField(max_length=20, verbose_name='审计单位部门名称')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '审计单位名称',
                'verbose_name_plural': '审计单位名称',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_image', models.ImageField(blank=True, default='users/image/u6.jpg', null=True, upload_to='users/image/%Y/%m', verbose_name='用户头像')),
                ('user_PQ', models.CharField(blank=True, max_length=100, null=True, verbose_name='职业资格')),
                ('user_phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机')),
                ('user_gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=10, verbose_name='性别')),
                ('user_birthday', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('leftbar_title', models.CharField(default='HeaderL_Fix', max_length=30, verbose_name='标题布局')),
                ('leftbar_option', models.CharField(default='sidebar-static-minified', max_length=30, verbose_name='边栏布局')),
                ('leftbar_titlecolor', models.CharField(default='HeaderB_Light', max_length=30, verbose_name='标题背景')),
                ('leftbar_navcolor', models.CharField(default='Sidebar2_Dark', max_length=30, verbose_name='导航背景')),
                ('leftbar_navposition', models.CharField(default='Siderbar2_Left', max_length=30, verbose_name='导航位置')),
                ('company_name', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='company_name1', to='users.CompanyInifo', verbose_name='审计单位')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
