# Generated by Django 3.0.5 on 2020-06-02 15:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlansInifo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_company', models.CharField(blank=True, max_length=50, null=True, verbose_name='被审计单位名称')),
                ('audit_person', models.CharField(blank=True, max_length=20, null=True, verbose_name='被审计人姓名')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('project_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='审计项目名称')),
                ('project_year', models.CharField(blank=True, max_length=5, null=True, verbose_name='项目年度')),
                ('plan_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='计划类型')),
                ('project_type', models.CharField(max_length=20, verbose_name='项目类别')),
                ('project_basis', models.TextField(blank=True, null=True, verbose_name='项目依据')),
                ('project_status', models.CharField(choices=[('pl', '准备'), ('st', '启动'), ('ex', '执行'), ('cp', '完成'), ('re', '整改'), ('cl', '关闭')], default='pl', max_length=10, verbose_name='项目阶段')),
                ('project_exaudit', models.BooleanField(default=False, verbose_name='是否外审')),
                ('project_exauditname', models.CharField(blank=True, max_length=50, null=True, verbose_name='外审组织名称')),
                ('status', models.BooleanField(default=True, verbose_name='逻辑删除')),
                ('company_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_name2', to='users.CompanyInifo', verbose_name='审计单位')),
            ],
            options={
                'verbose_name': '项目计划',
                'verbose_name_plural': '项目计划',
            },
        ),
        migrations.CreateModel(
            name='StartInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='逻辑删除')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('start_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='方案名称')),
                ('start_target', models.TextField(blank=True, null=True, verbose_name='审计目标')),
                ('start_range', models.TextField(blank=True, null=True, verbose_name='审计范围')),
                ('start_basis', models.TextField(blank=True, null=True, verbose_name='审计依据')),
                ('start_content', models.TextField(blank=True, null=True, verbose_name='审计内容')),
                ('start_progress', models.TextField(blank=True, null=True, verbose_name='审计程序')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='预计开始时间')),
                ('company_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_name5', to='users.CompanyInifo', verbose_name='审计单位')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_name7', to='plans.PlansInifo', verbose_name='项目名称')),
                ('start_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='username_2', to=settings.AUTH_USER_MODEL, verbose_name='编制人')),
            ],
            options={
                'verbose_name': '审计方案',
                'verbose_name_plural': '审计方案',
            },
        ),
        migrations.CreateModel(
            name='StartFieldInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_file', models.FileField(blank=True, null=True, upload_to='plans/file/%Y/%m', verbose_name='计划文件')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('status', models.BooleanField(default=True, verbose_name='逻辑删除')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_name5', to='plans.PlansInifo', verbose_name='项目名称')),
            ],
            options={
                'verbose_name': '项目启动附件',
                'verbose_name_plural': '项目启动附件',
            },
        ),
        migrations.CreateModel(
            name='AuditMemberInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('audit_role', models.CharField(choices=[('lvl1', '主审'), ('lvl2', '组员'), ('lvl3', '其他')], default='lvl2', max_length=10, verbose_name='审计角色')),
                ('status', models.BooleanField(default=True, verbose_name='逻辑删除')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_name3', to='plans.PlansInifo', verbose_name='项目名称')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='username1', to=settings.AUTH_USER_MODEL, verbose_name='审计成员')),
            ],
            options={
                'verbose_name': '审计成员信息',
                'verbose_name_plural': '审计成员信息',
            },
        ),
        migrations.CreateModel(
            name='AuditCompanyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_company', models.CharField(max_length=50, verbose_name='被审计单位名称')),
                ('audit_person', models.CharField(blank=True, max_length=20, null=True, verbose_name='被审计人姓名')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('status', models.BooleanField(default=True, verbose_name='逻辑删除')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_name1', to='plans.PlansInifo', verbose_name='项目名称')),
            ],
            options={
                'verbose_name': '被审计单位列表',
                'verbose_name_plural': '被审计单位列表',
            },
        ),
        migrations.CreateModel(
            name='AllNoticeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_name', models.CharField(max_length=60, verbose_name='通知书名称')),
                ('notice_type', models.CharField(choices=[('audit', '审计通知'), ('nomal', '日常通知'), ('report', '报告编号')], default='audit', max_length=10, verbose_name='通知类型')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('status', models.BooleanField(default=True, verbose_name='逻辑删除')),
                ('notice_NO', models.CharField(blank=True, max_length=20, null=True, verbose_name='通知书编号')),
                ('company_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_name3', to='users.CompanyInifo', verbose_name='审计单位')),
                ('project_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_name6', to='plans.PlansInifo', verbose_name='项目名称')),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='审计成员')),
            ],
            options={
                'verbose_name': '通知书',
                'verbose_name_plural': '通知书',
            },
        ),
        migrations.CreateModel(
            name='AllNoticeFileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_file', models.FileField(blank=True, null=True, upload_to='plans/notice/%Y/%m', verbose_name='通知附件')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('status', models.BooleanField(default=True, verbose_name='逻辑删除')),
                ('company_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_name4', to='users.CompanyInifo', verbose_name='审计单位')),
                ('notice_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notice_name1', to='plans.AllNoticeInfo', verbose_name='通知书名称')),
            ],
            options={
                'verbose_name': '通知书附件',
                'verbose_name_plural': '通知书附件',
            },
        ),
    ]
