# Generated by Django 3.0.5 on 2020-06-02 15:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('plans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('status', models.BooleanField(default=True, verbose_name='逻辑删除')),
                ('problem_title', models.CharField(blank=True, max_length=50, null=True, verbose_name='问题名称')),
                ('problem_content', models.TextField(blank=True, null=True, verbose_name='问题内容')),
                ('problem_feedback', models.TextField(blank=True, null=True, verbose_name='问题反馈')),
                ('problem_type', models.CharField(choices=[('sg', '建议'), ('re', '整改')], default='sg', max_length=10, verbose_name='问题类型')),
                ('problem_class', models.CharField(blank=True, max_length=20, null=True, verbose_name='问题分类')),
                ('problem_status', models.CharField(choices=[('do', '疑点'), ('el', '消除'), ('co', '确认')], default='do', max_length=10, verbose_name='问题状态')),
                ('audit_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plans.AuditCompanyInfo', verbose_name='被审计单位名称')),
                ('company_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_name12', to='users.CompanyInifo', verbose_name='审计单位')),
                ('project_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plans.PlansInifo', verbose_name='审计项目名称')),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='审计人员姓名')),
            ],
            options={
                'verbose_name': '问题详情',
                'verbose_name_plural': '问题详情',
            },
        ),
        migrations.CreateModel(
            name='RectificationPrjectInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('re_status', models.CharField(choices=[('pr', '整改中'), ('co', '整改完成')], default='pr', max_length=10, verbose_name='整改状态')),
                ('re_year', models.CharField(default='2020', max_length=5, verbose_name='年度')),
                ('status', models.BooleanField(default=True, verbose_name='逻辑删除')),
                ('company_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_name19', to='users.CompanyInifo', verbose_name='审计单位')),
                ('project_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plans.PlansInifo', verbose_name='审计项目名称')),
                ('report_NO', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_No', to='plans.AllNoticeInfo', verbose_name='报告编号')),
            ],
            options={
                'verbose_name': '整改项目',
                'verbose_name_plural': '整改项目',
            },
        ),
        migrations.CreateModel(
            name='ScheduleInifo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('schedule_title', models.CharField(blank=True, max_length=50, null=True, verbose_name='任务名称')),
                ('schedule_content', models.TextField(blank=True, null=True, verbose_name='任务内容')),
                ('schedule_feedback', models.TextField(blank=True, null=True, verbose_name='任务反馈')),
                ('start_time', models.DateField(default=datetime.datetime.now, verbose_name='任务开始时间')),
                ('end_time', models.DateField(default=datetime.datetime.now, verbose_name='任务结束时间')),
                ('status', models.BooleanField(default=True, verbose_name='逻辑删除')),
                ('audit_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plans.AuditCompanyInfo', verbose_name='被审计单位名称')),
                ('company_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_name11', to='users.CompanyInifo', verbose_name='审计单位')),
                ('project_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plans.PlansInifo', verbose_name='审计项目名称')),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='审计人员姓名')),
            ],
            options={
                'verbose_name': '任务详情',
                'verbose_name_plural': '任务详情',
            },
        ),
        migrations.CreateModel(
            name='ScheduleFileInifo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('status', models.BooleanField(default=True, verbose_name='逻辑删除')),
                ('schedule_file', models.FileField(blank=True, null=True, upload_to='plans/schedule/%Y/%m', verbose_name='记录文件')),
                ('audit_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plans.AuditCompanyInfo', verbose_name='被审计单位名称')),
                ('company_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_name13', to='users.CompanyInifo', verbose_name='审计单位')),
                ('project_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plans.PlansInifo', verbose_name='审计项目名称')),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='审计人员姓名')),
            ],
            options={
                'verbose_name': '项目附件',
                'verbose_name_plural': '项目附件',
            },
        ),
        migrations.CreateModel(
            name='ReportFileInifo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('status', models.BooleanField(default=True, verbose_name='逻辑删除')),
                ('report_file', models.FileField(blank=True, null=True, upload_to='plans/report/%Y/%m', verbose_name='问题文件')),
                ('report_type', models.CharField(choices=[('fi', '报告终稿'), ('fifi', '终稿附件'), ('pr', '报告过程稿'), ('prfi', '过程稿附件')], default='pr', max_length=10, verbose_name='报告类型')),
                ('company_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_name15', to='users.CompanyInifo', verbose_name='审计单位')),
                ('project_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plans.PlansInifo', verbose_name='审计项目名称')),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='审计人员姓名')),
            ],
            options={
                'verbose_name': '报告附件',
                'verbose_name_plural': '报告附件',
            },
        ),
        migrations.CreateModel(
            name='RectificationProblemInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('status', models.BooleanField(default=True, verbose_name='逻辑删除')),
                ('re_improve', models.TextField(blank=True, null=True, verbose_name='改进措施')),
                ('re_department', models.CharField(blank=True, max_length=20, null=True, verbose_name='整改责任部门')),
                ('re_person', models.CharField(blank=True, max_length=20, null=True, verbose_name='整改责任人')),
                ('re_date', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='整改完成时间')),
                ('re_situation', models.CharField(blank=True, choices=[('pr', '整改中'), ('co', '整改完成'), ('un', '无法整改')], default='pr', max_length=10, null=True, verbose_name='整改完成情况')),
                ('accountability_is', models.CharField(blank=True, choices=[('n', '否'), ('y', '是')], default='n', max_length=10, null=True, verbose_name='是否问责')),
                ('accountability_content', models.TextField(blank=True, null=True, verbose_name='问责情况')),
                ('announcement_is', models.CharField(blank=True, choices=[('n', '否'), ('y', '是')], default='n', max_length=10, null=True, verbose_name='是否公告')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('company_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_name17', to='users.CompanyInifo', verbose_name='审计单位')),
                ('re_problem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problem_info', to='ex.ProblemInfo', verbose_name='整改问题')),
                ('re_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='re_project', to='ex.RectificationPrjectInfo', verbose_name='整改项目')),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='审计人员姓名')),
            ],
            options={
                'verbose_name': '整改问题',
                'verbose_name_plural': '整改问题',
            },
        ),
        migrations.CreateModel(
            name='RectificationFeedbackInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('status', models.BooleanField(default=True, verbose_name='逻辑删除')),
                ('re_improve', models.TextField(blank=True, null=True, verbose_name='改进措施')),
                ('re_department', models.CharField(blank=True, max_length=20, null=True, verbose_name='整改责任部门')),
                ('re_person', models.CharField(blank=True, max_length=20, null=True, verbose_name='整改责任人')),
                ('re_date', models.DateField(default=datetime.datetime.now, verbose_name='整改完成时间')),
                ('re_situation', models.CharField(choices=[('pr', '整改中'), ('co', '整改完成'), ('un', '无法整改')], default='pr', max_length=10, verbose_name='整改完成情况')),
                ('accountability_is', models.CharField(choices=[('n', '否'), ('y', '是')], default='n', max_length=10, verbose_name='是否问责')),
                ('accountability_content', models.TextField(blank=True, null=True, verbose_name='问责情况')),
                ('announcement_is', models.CharField(choices=[('n', '否'), ('y', '是')], default='n', max_length=10, verbose_name='是否公告')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('company_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_name21', to='users.CompanyInifo', verbose_name='审计单位')),
                ('re_project_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problem_info1', to='ex.RectificationProblemInfo', verbose_name='整改问题')),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='审计人员姓名')),
            ],
            options={
                'verbose_name': '整改回复',
                'verbose_name_plural': '整改回复',
            },
        ),
        migrations.CreateModel(
            name='RectificationFeedbackFileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('status', models.BooleanField(default=True, verbose_name='逻辑删除')),
                ('re_file', models.FileField(blank=True, null=True, upload_to='re/feedback/%Y/%m', verbose_name='问题文件')),
                ('company_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_name18', to='users.CompanyInifo', verbose_name='审计单位')),
                ('re_feedback', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ex.RectificationFeedbackInfo', verbose_name='整改回复')),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='审计人员姓名')),
            ],
            options={
                'verbose_name': '整改附件',
                'verbose_name_plural': '整改附件',
            },
        ),
        migrations.CreateModel(
            name='ProblemFileInifo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('status', models.BooleanField(default=True, verbose_name='逻辑删除')),
                ('problem_file', models.FileField(blank=True, null=True, upload_to='plans/problem/%Y/%m', verbose_name='问题文件')),
                ('audit_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plans.AuditCompanyInfo', verbose_name='被审计单位名称')),
                ('company_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_name14', to='users.CompanyInifo', verbose_name='审计单位')),
                ('problem_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ex.ProblemInfo', verbose_name='问题编号')),
                ('project_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plans.PlansInifo', verbose_name='审计项目名称')),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='审计人员姓名')),
            ],
            options={
                'verbose_name': '问题附件',
                'verbose_name_plural': '问题附件',
            },
        ),
        migrations.CreateModel(
            name='FeedbackFileInifo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('status', models.BooleanField(default=True, verbose_name='逻辑删除')),
                ('feedback_file', models.FileField(blank=True, null=True, upload_to='plans/feedback/%Y/%m', verbose_name='征求意见附件')),
                ('feedback_type', models.CharField(choices=[('se', '征求'), ('fe', '反馈')], default='se', max_length=10, verbose_name='过程类型')),
                ('company_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_name16', to='users.CompanyInifo', verbose_name='审计单位')),
                ('project_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plans.PlansInifo', verbose_name='审计项目名称')),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='审计人员姓名')),
            ],
            options={
                'verbose_name': '征求意见',
                'verbose_name_plural': '征求意见',
            },
        ),
    ]
